services:
    _defaults:
        autowire: true
        autoconfigure: true

    Nelmio\ApiDocBundle\Render\RenderOpenApi: '@nelmio_api_doc.render_docs'

    App\:
        resource: '../src/'

#    App\Domain\Task\Repository\TaskRepositoryInterface:
#        alias: App\Infrastructure\Task\Repository\DoctrineTaskRepository
